/*
 * File: stats.interface.ts
 * Project: covid-tracker
 * Description:
 * File Created: Saturday, 4th April 2020 12:00:37 am
 * Author: Adithya Sreyaj
 * -----
 * Last Modified: Saturday, 4th April 2020 12:00:39 am
 * Modified By: Adithya Sreyaj<adi.sreyaj@gmail.com>
 * -----
 */

// Generated by https://quicktype.io

export interface WorldStats {
  cases: number;
  deaths: number;
  recovered: number;
  updated: number;
  active: number;
  affectedCountries: number;
}
